project:
  type: website

website:
  title: "Margarita Vald√©s A., PhD"
  description: "This is Margarita Valdes' personal Data Analysis portfolio"
  site-url: "https://margar1tava.quarto.pub/portfolio/"
  favicon: "profile.jpg"
  page-footer: 
    left:
      [made with Quarto]
  navbar:
    background: light
    right: 
      - text: Portfolio
        href: blog.qmd
      - text: Resume
        href: resume.qmd
      - icon: github
        href: https://github.com/MARgar1taVA
      - icon: linkedin
        href: https://www.linkedin.com/in/m-valdes-aleman/
      - icon: clipboard-data-fill
        href: https://public.tableau.com/app/profile/margarita.vald.s.alem.n/vizzes
      - icon: envelope-fill
        href: mailto:valdes.aleman.margarita@gmail.com 

highlight-style: ayu
theme: 
  - cosmo
  - styles.scss

editor: visual

